### ISSUE TITLE
Unitz ideas and enhancement concepts (mainly method chaining)

### ISSUE THREAD

**Issue by jfrux** [ClickerMonkey/unitz#10]
So I wanted to move this over to a new issue so that we don't goop up that other issue too much.

However, here is what I suggest for possibly making the library a bit more dev-friendly.

I'm not sure if nesting the methods to get a final value is the way to go.

### Method Chaining
Possibly as a better option we could add a Unitz.String class that extends the base string object.
We would use it in place of any String that is returned currently.
It could extend the base javascript string object as well so it would still have those aspects.

This String object will allow us to chain off of things like "combine" and "compound".
But not just String would be chainable.

Currently, we must do this:
`Unitz.parse(Unitz.combine("3.25 cups, 1.5 tbsp"));`
Which could be expressed as:
`Unitz.combine("3.25 cups, 1.5 tbsp").parse();`

You could take it a step further and get the fraction since you already have the fraction coming off of the `parse()` already.

It may, make sense to just turn everything into a base Unitz instance and fire off the chains from there.

For instance, in Moment.js, a "Moment" can do all sorts of magical things.

Perhaps maybe instead of having to parse it, we could also just parse as the default.

`Unitz("3.25 cups, 1.5 tbsp");`

This could just always return a "parsed" amount.

Unitz("3.25 cups, 1.5 tbsp");

Would simply run `return Unitz.combine("3.25 cups, 1.5 tbsp").parse()`

### Library Configuration

In Moment.js, everything is configured through locale, which may or may not be a good way to do it for this.

Essentially, however, we could have it able to house per-app settings for the overrides instead of overriding the base-config.

I think something like this makes sense...
```javascript
unitz.settings('my-app-settings', {
    // customizations.
});

// Removes previously defined settings list
unitz.settings('my-app-settings',null)
```

**Comment by jfrux** [comment]
Sorry, got cut off by someone - I'll review my thoughts a bit later too and update my post

**Comment by ClickerMonkey** [comment]
I'm not ignoring you, I'm just letting these ideas stew until a nice solution strikes me!

**Comment by jfrux** [comment]
Wouldn’t have it any other way!
I’ve been kind of wrapped up in a project honestly so haven’t been back to this just yet.
But the project does involve this so it’ll get picked back up very soon I’m sure.

**Comment by ClickerMonkey** [comment]
Still letting this stew

**Comment by ClickerMonkey** [comment]
I'm working on my ideas here:

https://github.com/ClickerMonkey/unitz/wiki/Design-v2

Basically you would give Unitz a string, perform some operations on it, then eventually call a function which outputs what you want.

**Comment by jfrux** [comment]
So I'm back at it again...

I'm using compound and when I pass "2 ounces" with ["oz","lb"] as the options, it is returning `2/16 lb`... anyway to make it return `2 oz`?  Not sure where the threshold should be...

**Comment by jfrux** [comment]
```
let lbs = Math.floor(parsed.value / 16);
          let oz = parsed.value % 16;
          // console.log(remainder);
          // let dec = lbs - ;
          console.log(lbs);
          console.log(oz);
          compound = `${lbs} lb, ${oz} oz`;
```

**Comment by jfrux** [comment]
Somehow I just need to get that as the result haha

**Comment by jfrux** [comment]
My bad, looks like I had outdated library...

**Comment by ClickerMonkey** [comment]
@joshuairl I'm working on v2 and hope to be finished some time this week!

**Comment by ClickerMonkey** [comment]
Checkout https://github.com/ClickerMonkey/unitz-ts when you have time @joshuairl !
