### ISSUE TITLE
Is there a way to output the short version of a unit name instead of the long version?

### ISSUE THREAD

**Issue by jfrux** [ClickerMonkey/unitz#12]
I'd like to make it so that when I do a "combine" I can tell it to use the short unit name (abbreviation) instead of spelling it out.

I'm guessing this wouldn't be tricky but couldn't see if there was a setting for it.

**Comment by ClickerMonkey** [comment]
Adding to the todo list!

**Comment by ClickerMonkey** [comment]
Release 0.6.0 has an argument you can pass. Check out the updated documentation!

http://clickermonkey.github.io/unitz/Unitz.html#.combine
