### ISSUE TITLE
convert to 'cl' or 'dl' ?

### ISSUE THREAD

**Issue by abate** [ClickerMonkey/unitz#13]
Is it possible to convert to cl or dl ? I've the impression that centilitres and deciliter are missing from the conversion class ... Is this on purpose ?

thx !

**Comment by abate** [comment]
and also, is there a way to add cl to the volume class thought the api ?
something along these lines maybe ?
```

volumeUC = Unitz.classes[5]
volumeUC.addGroup( 100, 'cl', ['cl', 'centilitre', 'centilitres'], [2, 10], 'centilitre', 'centilitres' )
```

**Comment by ClickerMonkey** [comment]
Yes - that would be it. I'll add it to the volume class!

**Comment by ClickerMonkey** [comment]
Release 0.5.1 created.
