### ISSUE TITLE
mix oz and fl oz in Volume

### ISSUE THREAD

**Issue by abate** [ClickerMonkey/unitz#14]
Hi,

I'm not sure if this is correct, but you mix oz (mass) and fl oz (volume) in
['oz', 'ounce', 'ounces', 'fl-oz', 'fl oz', 'floz', 'fluid ounce', 'fl. oz.', 'oz. fl.', 'oz fl']

I'm trying to parse something like "10 oz" and when normalized it gives me back
"10 fluid oz" that in my view it is not quite right. 

shouldn't the line above be just 
[''fl oz', 'fl-oz', 'floz', 'fluid ounce', 'fl. oz.', 'oz. fl.', 'oz fl']

?

**Comment by ClickerMonkey** [comment]
I'm mixed on this one - but I understand the confusion. Sometimes people colloquially say/write oz when they really mean fl oz. I'll remove oz from the fluid ounce class but add a function to add colloquial units to appropriate groups.

**Comment by ClickerMonkey** [comment]
If removing the unit from volume solves your problem, you can with code.

```
Unitz.classMap.Volume.removeUnit('oz');
Unitz.classMap.Volume.removeUnit('ounce');
Unitz.classMap.Volume.removeUnit('ounces');
Unitz.unitToClass.oz = Unitz.classMap.Weight;
delete Unitz.unitToClass.ounce
delete Unitz.unitToClass.ounces
```


I'll make sure to retain this functionality (and make it friendlier) in Unitz v2.
