### ISSUE TITLE
compound but on whole numbers instead of fractions?

### ISSUE THREAD

**Issue by jfrux** [ClickerMonkey/unitz#15]
I forked the repo to try to solve this but I'm just not versed enough in this kind of math I guess...

Trying to get it to always prefer whole number for the larger units and only create fractions when absolutely necessary...

Rather than doing like...
`1/2 lb, 4 oz` I'd prefer it to do `12 oz`

Is there something I can easily change about it in the interim to get this result?

**Comment by jfrux** [comment]
Nvm... that's not what I'm wanting... I guess I'm just trying to build a rule around each unit and when it should break...

I mean obviously on a recipe I wouldn't want to list 47 ounces, so I guess I just need to find a good happy medium.

Wondering if I should add properties to the `group` object for the "ingredient breakpoint".
And then copy the compound function but do like a `grouped_volume` or something.

I know my names aren't great... trying to think this out, it may be outside of the scope of this library to be honest.

**Comment by ClickerMonkey** [comment]
Thanks for the input, I'm working on v2 of the library and I will add a "threshold" property on the group/output options so you can customize this sort of thing! It should be available in an early form this week sometime.

**Comment by ClickerMonkey** [comment]
This has been addressed in https://github.com/ClickerMonkey/unitz-ts
