### ISSUE TITLE
Unitz.Fraction shows the wrong output

### ISSUE THREAD

**Issue by xenjogmbh** [ClickerMonkey/unitz#16]
ok:
console.log(new Unitz.Fraction(1.05, [2, 3, 4, 8, 16]).string); 
1 1/16

wrong:
console.log(new Unitz.Fraction(1.05, [2, 3, 4, 8]).string);
1.05

I have installed "unitz": "^0.5.1" and tested it with node v9.11.1

**Comment by ClickerMonkey** [comment]
Unitz tries to determine a fraction within a certain amount (Unitz.epsilon) and if it cannot then the numerator is the value passed in and the fraction is marked as not valid (there's a valid property on the fraction). So either you need to return more possible denominators, or accept that some numbers can not sufficiently be represented as fractions. If you have 0.75 and say the only possible denominator is 2, would you want `1` or `1/2` ? Both are equally away, and both are way off.

Just to let you know, a new (major) version of this library will be released within a week. It will be in typescript but obviously have a javascript version.
