### ISSUE TITLE
upload version 0.6.0 on npmjs.com

### ISSUE THREAD

**Issue by abate** [ClickerMonkey/unitz#17]
the version here is still 0.5.1 ... Is it possible to update it with the latest version ?

https://www.npmjs.com/package/unitz

thanks !

**Comment by ClickerMonkey** [comment]
Done!

I would recommend migrating to https://github.com/ClickerMonkey/unitz-ts, it has far more functionality and is a lot easier to use IMO. This library was written in TypeScript but can be used in JS. Fully documented with a nice online tool for testing user input and configuration.
