### ISSUE TITLE
Wrong digital units

### ISSUE THREAD

**Issue by alebianco** [ClickerMonkey/unitz#6]
The units to convert digital information do not conform with the standard 
see https://en.wikipedia.org/wiki/Kibibyte and https://en.wikipedia.org/wiki/Kilobit

usually B (uppercase) is used for bytes and b (lowecase) is used for bits

K means times 1000
Ki means times 1024

so 1 kB = 1000B = 8000b
and 1 KiB = 1024B = 8192b
and 1kb = 1000b

it does little difference on small values, but once you get to T it could be substantial. does not matter much to the end user but for the purpose of calculations it's important

**Comment by ClickerMonkey** [comment]
Thank for the correction!

At the moment case is ignored by Unitz but with a few tweaks it should be able to handle them. Thanks for pointing this out - I knew the conversions were a little off but I wasn't sure at the time if I wanted to support cased units.

**Comment by alebianco** [comment]
I think you can get away with the upper/lower case scenarios
even google uses kb and kB as the same unit. I think it uses kbit when it comes to bits, which is a sound alternative i think

**Comment by ClickerMonkey** [comment]
Released:

https://github.com/ClickerMonkey/unitz/releases/tag/0.4.1
