### ISSUE TITLE
Is there a way to just take a non-mapped unit amount and make it a fraction?

### ISSUE THREAD

**Issue by jfrux** [ClickerMonkey/unitz#9]
Say I have an item like `5.5 packages`.
Unitz parses it as 5.5 value and packages as unit.

Is there no way to just make this a fraction like `5 1/2 packages`?

**Comment by ClickerMonkey** [comment]
I've added .fraction() to the parsed value, it will be committed shortly.

**Comment by ClickerMonkey** [comment]
Release 0.5.0 was created and is accessible on NPM and Bower

**Comment by jfrux** [comment]
It appears certain fractions don't want to convert...
Simple number like "1.5" seems to just stay that way in the fraction string.
![image](https://cloud.githubusercontent.com/assets/171077/24531769/3900e388-1589-11e7-94a7-1bc0ac52637b.png)

**Comment by ClickerMonkey** [comment]
You should pass valid denominators to the `fraction()` function like so:

```
Unitz.parse('1.5 packages').fraction( true, [2, 3, 4, 5, 6, 7, 8, 9, 10] ).string; // '1 1/2 packages'
```

This may seem odd, but for performance reasons and readability (we don't want fractions like 23/8979) I decided you can supply denominators you're okay with.

**Comment by ClickerMonkey** [comment]
If you have a good idea on the different units your application will have - you can add your classes/groups yourself so it automatically knows which denominators are okay (and can properly pluralize):

For example:

https://raw.githubusercontent.com/ClickerMonkey/unitz/master/src/classes/weight.js

(add `Unitz.` before `addClass`)

**Comment by jfrux** [comment]
Thanks!

I thought about that, but I couldn’t find documentation on how to add my own classes properly…
Any tips on this?

**Comment by ClickerMonkey** [comment]
If you look at my edit above - you can see how they're done. Its a little cryptic until you look at the function definition... then it's still a little cryptic.

Basically you start with your base unit - which is the smallest unit in a class. A class is like "Volume" or "Weight". A group is like "Inch" or "Centimeter" which are in the "Length" class.

You could have different systems (imperial vs metric) so you can add Base conversions between the base units (mm and in).

```
var uc = new Unitz.Class( 'My Class' );

// uc.addGroup( valueRelativeToBaseUnit, baseUnit, unitsAvailableFirstOneIsMainUnit, validDenominators, singular, plural )
uc.addGroup( 1,       null,     ['mg', 'milligram', 'milligrams'], [2, 10], 'milligram', 'milligrams' );
uc.addGroup( 1000,    'mg',     ['g', 'gram', 'grams'], [2, 10, 100], 'gram', 'grams' );

Unitz.addClass( uc );
```
